# spring.application.name=entry-checkout
# # MySQL connection - change username/password to match your MySQL
# spring.datasource.url=jdbc:mysql://localhost:3306/companydb?createDatabaseIfNotExist=true
# spring.datasource.username=root
# spring.datasource.password=Sahkaran@514

# # Automatically creates the "users" table for us based on the User entity
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://dpg-d9e9u8bbc2fs73fihms0-a.singapore-postgres.render.com:5432/ems_database_x2hk
spring.datasource.username=ems_database_x2hk_user
spring.datasource.password=ALhOb1EV545g3paLrlxharSaARSzz4os
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Optional with Hibernate 7 / Spring Boot 4:
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080