spring.application.name=entry-checkout
# MySQL connection - change username/password to match your MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/companydb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Sahkaran@514

# Automatically creates the "users" table for us based on the User entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true